
metadata:
  name:  ${service.name}
  annotations:
    fabric8.io/iconUrl: >-
      ${icon}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        version: ${project.version}
      annotations:
        fabric8.io/iconUrl: >-
          {icon}
    spec:
      containers:
      - env:
        - name: COUCH_USERNAME
          value: redhat
        - name: COUCH_PASSWORD
          value: redhat123
        - name: COUCH_SERVICE
          value: "http://couchdb:5984/"
        - name: COUCH_TIMEOUT
          value: 3000
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /vote
            port: ${container.port}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
