
metadata:
  name:  ${service.name}
  annotations:
    fabric8.io/iconUrl: >-
      ${icon}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        version: ${project.version}
      annotations:
        fabric8.io/iconUrl: >-
          {icon}
    spec:
      containers:
        - readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /speaker
            port: ${container.port}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
