apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-authz
    version: v1
  name: microservice-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-authz
      version: v1
  template:
    metadata:
      labels:
        app: microservice-authz
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms64m -Xmx128m -Dswarm.logging=DEBUG -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        - name: JAR_SHA256
          value: JAR_SHA256_VALUE
        image: example/microservice-authz:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        name: microservice-authz
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
